{{- if .Values.gatewayClass.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName | quote }}
  {{- with .Values.gatewayClass.description }}
  description: {{ . | quote }}
  {{- end }}
  {{- with .Values.gatewayClass.parametersRef }}
  parametersRef:
    {{- if .group }}group: {{ .group | quote }}{{- end }}
    kind: {{ .kind | quote }}
    name: {{ .name | quote }}
    {{- if .namespace }}namespace: {{ .namespace | quote }}{{- end }}
  {{- end }}
{{- end }}
